name: 'AI API Key Scanner'
description: 'Scans PR diffs for OpenAI, Anthropic, and Google AI API keys'
author: 'GitHub'
branding:
  icon: 'shield'
  color: 'red'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  config-path:
    description: 'Path to configuration file'
    required: false
    default: '.github/ai-key-scanner.yml'
runs:
  using: 'node20'
  main: 'dist/index.js'

